### ISSUE TITLE
Footnote counter starts at 2 and links to title page. 

### ISSUE THREAD

**Issue by retogaeh** [TUT-ASI/thesis-template#13]
First appearance of footnote has count 2 instead of 1. 

Link doesn't take focus to the page's footer but rather to title page!

**Comment by AlexDaniel** [comment]
I think this is the problem: https://tex.stackexchange.com/a/72691

**Comment by AlexDaniel** [comment]
OK, so this can be fixed by commenting out `\usepackage[perpage]{footmisc}` and making sure that `\usepackage{hyperref}` is the last used package. This way the numbering starts from 1 and links are pointing at the end of the page. However, the numbering of footnotes is then global, and that contradicts the guidelines:

![image](https://user-images.githubusercontent.com/5507503/53837990-acea6000-3f9c-11e9-968f-96c5069a960a.png)

**Comment by AlexDaniel** [comment]
Fixed it by using `perpage` package.
